[project]
name = 'BitcoinDice'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.grand-nft]
path = 'contracts/grand-nft.clar'
clarity_version = 2
epoch = 2.4

[contracts.lottery-1]
path = 'contracts/lottery-1.clar'
clarity_version = 2
epoch = 2.4

[contracts.lottery-1-prize]
path = 'contracts/lottery-1-prize.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
